version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: nycu-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=production
      - DATABASE_URL=sqlite:///./courses.db
    volumes:
      - ./backend/courses.db:/app/courses.db
    restart: unless-stopped
    networks:
      - nycu-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: nycu-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
      - NODE_ENV=production
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - nycu-network

  nginx:
    image: nginx:alpine
    container_name: nycu-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - nycu-network

networks:
  nycu-network:
    driver: bridge
