# Kubernetes ConfigMap - Environment Variables and Configuration
# Non-sensitive configuration data

apiVersion: v1
kind: ConfigMap
metadata:
  name: nycu-platform-config
  namespace: nycu-platform
  labels:
    app: nycu-course-platform
data:
  # Backend Configuration
  API_HOST: "0.0.0.0"
  API_PORT: "8000"
  LOG_LEVEL: "info"

  # Frontend Configuration
  NODE_ENV: "production"
  NEXT_TELEMETRY_DISABLED: "1"

  # Database Configuration (non-sensitive)
  POSTGRES_DB: "nycu_courses"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"

  # Redis Configuration
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"

  # Application Settings
  APP_NAME: "NYCU Course Platform"
  APP_VERSION: "1.0.0"
  ENVIRONMENT: "production"
